### ISSUE TITLE
使用@JsonInclude注解过滤无用属性前台不生效，请支持该属性

### ISSUE THREAD

**Issue by tianlige** [spring-cloud/spring-cloud-circuitbreaker#112]
使用@JsonInclude注解过滤无用属性前台不生效，请支持该属性

**Comment by ryanjbaxter** [comment]
Please provide an english translation

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
