### ISSUE TITLE
circuit-breaker configuration with feign interceptor to share security context

### ISSUE THREAD

**Issue by bdi-gud** [spring-cloud/spring-cloud-circuitbreaker#123]
Hello!
I am having some issues to configure the spring cloud circuit-breaker with resilience4j and the security context. I need to retrieve a token with a feign interceptor.
I was on Hystrix and the configuration were simple with property shareSecurityContext.

I understand that the cicruit breaker should not create a new thread in contrary to Hystrix. A new thread is created when we use Bulkhead which should be activated when found in the classpath as explain in the documentation.

In my project, I have included only org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j and the Bulkhead should not be used. During my tests I noted that a new thread is created and the security context is null in the interceptor. I did not see any clue that the Bulkhead was activated. Contrary to Bulkhead I did not find any 
property to setup the context propagation with the circuit-breaker.

Is it a normal behaviour or is there something that I have missed in the configuration or documentation ?

Thank you in advance

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by bdi-gud** [comment]
[spring-cloud-circuitbreaker-open-feign.zip](https://github.com/spring-cloud/spring-cloud-circuitbreaker/files/7558177/spring-cloud-circuitbreaker-open-feign.zip)

Please find in attachment a sample based on the circuit-breaker demo. I added spring cloud open feign and a request interceptor. I also logged the thread id.

**Comment by koehleru** [comment]
i have the same problem. 
i set the SecurityContextHolder-strategy

`SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);`

but the in the RequestIntercepter the Authentication is still null.

**Comment by koehleru** [comment]
@ryanjbaxter any news? can you reproduce the problem?

**Comment by ryanjbaxter** [comment]
Its on my list to look at, things have been busy

**Comment by koehleru** [comment]
i checked this behavior again and i think it is not a bug.
@bdi-gud in your example you have to set 
`SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);`
globaly some in a `Configuration` and then the propagation of `SecurityContext` to the child thread from the CircuitBreaker works. this copy the SecurityContext to the new thread.

In my setup  i have a different problem. i have two FeignClients.
When the first FeignClient is called, the Authentication is not set in the SecurityContext. So the CircuitBreaker creates a new thread with Authentication is null. When the call to the second FeignClient happens, the Authentication is set in the "main" thread, but the CircuitBreaker reuse the thread from the first call with the Authentication is null. the threadlocals variabales are only copied when a new thread is created. 
at the moment i have no idea how to force the CircuitBreaker

**Comment by koehleru** [comment]
i found a bettwer way.
configure the `Resilience4JCircuitBreakerFactory` to use a `DelegatingSecurityContextExecutorService`

	@Bean
	public Customizer<Resilience4JCircuitBreakerFactory> defaultCustomizer() {
		return factory -> factory.configureExecutorService(new DelegatingSecurityContextExecutorService(Executors.newCachedThreadPool()));
	}

so the SecurityContext is propagate the the child thread for the CircuitBreaker.
with the SecurityContext strategy 
`SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);`
you can get security issues, because the Context is only propagted when a new child thread is created.

**Comment by bdi-gud** [comment]
@koehleru Your solution works fine. Thank you for your input.

`SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_INHERITABLETHREADLOCAL);` was problematic in my setup with scheduled tasks.
