### ISSUE TITLE
Checked exception handling missing

### ISSUE THREAD

**Issue by camproto** [spring-cloud/spring-cloud-circuitbreaker#143]
Checked exceptions are not possible with the cbFactory.create("...").run( () -> ...) pattern. 
Sometimes this is needed, maybe because of generated code or older code, which would be hard to re-work. 

I want to replace @HystrixCommand (with supports checked exceptions) and have several methods with checked exceptions. 

I use it with R4J and there is a possibility going this style 

```
    public BerichtsdatenResponse kontrollberichtUebertragen(Bericht bericht) throws Fehler_Exception {

        CircuitBreakerTemplate<BerichtsdatenResponse, Fehler_Exception> template =
            new CircuitBreakerTemplate<>("scowi-kb", Fehler_Exception.class);
        return template.circuitBreak(() -> getBerichtUebertragenResponse(bericht));
    }
```
using this self written template
```
    @SuppressWarnings("unchecked")
    public R circuitBreak(CheckedFunction0<R> supplier) throws E {
        var checkedSupplier = CircuitBreaker.decorateCheckedSupplier(circuitBreaker, supplier);

        Try<R> responseTry = Try.of(checkedSupplier);
        if (responseTry.isFailure()) {
            throw (E) responseTry.getCause();
        }
        return responseTry.get();
    }
```
Your run() used only 
`return Try.of(callable::call).recover(fallback).get();`

Do you see a way for a workaround right now? 

Suggest to add another run method making handling of checked exceptions straightforward.

**Comment by ryanjbaxter** [comment]
Sorry I am not following, can you provide and example that reproduces the problem?

**Comment by camproto** [comment]
Sorry, forgot the original method I need to decorate

`@HystrixCommand(commandKey = "kb", groupKey = "bv", ignoreExceptions = Fehler_Exception.class)
    public berichtsdatenResponse kontrollberichtUebertragen(Bericht bericht) throws Fehler_Exception {
...
}`

Problem is the checked exception, which at the end is caused by a generated SOAP service. I cannot re-work all the existing code around this exception handling. 

Is there a way to decorate methods with checked exceptions?

**Comment by ryanjbaxter** [comment]
So you want the circuit breaker to ignore `Fehler_Exception`?

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by camproto** [comment]
I could find a solution using the sneaky throws "feature" of java build into Try.of().get().
