### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by sergey-morenets** [spring-cloud/spring-cloud-circuitbreaker#149]
The Demo project (https://github.com/spring-cloud-samples/spring-cloud-circuitbreaker-demo) contains outdated documentation. 

It seems that Hystrix support was dropped but README.md still states about Hystrix support and examples:

`There are two non-reactive samples in this repo, spring-cloud-circuitbreaker-hystrix and spring-cloud-circuitbreaker-resilience4j.`

```
There are three reactive samples in this repo, spring-cloud-circuitbreaker-demo-reactive, spring-cloud-circuitbreaker-demo-reactive-hystrix, and spring-cloud-circuibreaker-demo-reactive-resilience4j.
Hystrix and Resilience4J Reactive Samples
```

**Comment by ryanjbaxter** [comment]
Thanks
https://github.com/spring-cloud-samples/spring-cloud-circuitbreaker-demo/commit/faafc24da64df3a6a2b2bc2dffaf68342839a626
