### ISSUE TITLE
Resilience4jFeign does not work in release train 2022.0.5

### ISSUE THREAD

**Issue by ifdrmg** [spring-cloud/spring-cloud-circuitbreaker#184]
**Describe the bug**
Resilience4jFeign builder does not work in latest 2022.0.5 release train, due to incompatible changes in `Feign.Builder`.  The result is that circuit breakers are not applied.

This [change](https://github.com/OpenFeign/feign/commit/fc6daef95fdde3aaf9d4ba10f36331876c6eead2#diff-3ed37071fe69a1f75569397664c1dc266951c93614b28a8e25d7f2ad16525949R286) made `build()` final in `BaseBuilder`, and introduced a new `internalBuild()` method that can be overriden instead. Resilience4jFeign still overrides `build()`, but the overriden version does not get called.

**Comment by ryanjbaxter** [comment]
This issue appears to be meant for this project https://github.com/resilience4j/resilience4j

**Comment by ifdrmg** [comment]
For future readers of this thread, there's already an issue filed there: https://github.com/resilience4j/resilience4j/issues/2126
