### ISSUE TITLE
spring-boot-starter-aop missing

### ISSUE THREAD

**Issue by mgimenoromanadevinta** [spring-cloud/spring-cloud-circuitbreaker#187]
**Describe the bug**
Since `org.springframework.cloud:spring-cloud-dependencies:2023.0.2` the dependency `org.springframework.boot:spring-boot-starter-aop` has been removed from `org.springframework.cloud:spring-cloud-starter-openfeign`.

This is causing this circuit breaker library to not work properly if it's not added manually into the build file (circuits are always closed, etc)

[An issue was raised](https://github.com/spring-cloud/spring-cloud-openfeign/issues/1035) to openfeign and they answered that they don't plan to add it back and that it should be in the libraries that require it (in this case, this one it seems)

Is this something that you're aware of? Is there a plan to fix it?

Thank you very much

**Comment by ryanjbaxter** [comment]
Are you using Resilience4J annotations and that is why you need `spring-boot-starter-aop`?
https://resilience4j.readme.io/docs/getting-started-3#annotations

**Comment by mgimenoromanadevinta** [comment]
Hello @ryanjbaxter 

Yes indeed, we're using annotations such as @CircuitBreaker

**Comment by ryanjbaxter** [comment]
That is not functionality provided by Spring Cloud CircuitBreaker not Spring Cloud OpenFeign the requirement is coming from Resilience4J.  So I do not believe we should be including the AOP started in the Spring Cloud projects.
