### ISSUE TITLE
Stable versioned documentation links

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-circuitbreaker#189]
I maintain some internal documentation that contains links to Spring Cloud Circuitbreaker documentation for different versions of Spring Cloud Circuitbreaker.

It used to be possible to link to https://docs.spring.io/spring-cloud-circuitbreaker/docs/${version}/reference/html/, but after version 3.0.4 this stopped working. Looking at https://docs.spring.io/spring-cloud-circuitbreaker/docs/ I found that documentation now seems to be published per minor version, so I thought I should now link to https://docs.spring.io/spring-cloud-circuitbreaker/docs/3.1.x/reference/html/. However, this link seems to contain the documentation for version 3.1.0-M1 and not the latest 3.1.x (currently 3.1.2). Am I correct that https://docs.spring.io/spring-cloud-circuitbreaker/docs/3.1.x/reference/html/ is intended to host the latest 3.1.x version?

**Comment by ryanjbaxter** [comment]
> Am I correct that https://docs.spring.io/spring-cloud-circuitbreaker/docs/3.1.x/reference/html/ is intended to host the latest 3.1.x version?

No this is not correct.  In the process of doing the 3.1.x release we switch to a new platform for documentation and it is now placed in a different location.  This is why the latest and previous releases of 3.1.x are not in that directory.  

If you go to https://docs.spring.io/spring-cloud-circuitbreaker/reference/3.1/index.html You will see the latest release for the 3.1.x branch and if you go to https://docs.spring.io/spring-cloud-circuitbreaker/reference/3.1-SNAPSHOT/index.html you will see the latest snapshot release for the 3.1.x branch

**Comment by breun** [comment]
Ah ok, thanks for those new links. It looks like https://spring.io/projects/spring-cloud-circuitbreaker#learn still links to the old style URLs.

**Comment by ryanjbaxter** [comment]
Thanks for the heads up, it should be fixed now.
