### ISSUE TITLE
Issue in timeout-duration sintax using .yml

### ISSUE THREAD

**Issue by Stevenrq** [spring-cloud/spring-cloud-circuitbreaker#229]
I had an syntax error in the **timelimiter** specifically in the **timeout-duration**. I am using spring-cloud-starter-circuitbreaker-resilience4j version 3.2.0. This problem only occurs when the timeout-duration is not on a single line.

The error is as follows:
**Caused by**: io.github.resilience4j.core.ConfigurationNotFoundException: Configuration with name 'default' does not exist

![{1BE865F5-D94F-4CFF-A55E-737E296F60DD}](https://github.com/user-attachments/assets/4afe9145-b1e6-4914-b696-1a87f8477600)

This is my example configuration:
``` java
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 20
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold:
          seconds: 3
        slow-call-rate-threshold: 50
    instances:
      items:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 4
    instances:
      items:
        base-config: default
```

I solved this by modifying the timeout-duration in one line as shown below:

``` java
  timelimiter:
    configs:
      default:
        timeout-duration: 4s
    instances:
      items:
        base-config: default
```

I don't understand why this only happens in the timelimiter since the rest of the code works correctly.

**Comment by ryanjbaxter** [comment]
Nothing in that stacktrace points to Spring Cloud CircuitBreaker.  This seems like an issue with Resilience4J specifically.

**Comment by Stevenrq** [comment]
I understand, I wanted to make this problem clear since I have done several tests and this was the solution I found.

**Comment by ryanjbaxter** [comment]
Sure, I am going to close this issue then since it does not appear to be a problem with this project.
