### ISSUE TITLE
Resilience4J and Feign Support

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-circuitbreaker#3]

**Comment by arnokoehler** [comment]
20 Dec 2018 This is not really a priority as it seems? Why not if I may ask?

**Comment by mraible** [comment]
Has progress been made on this issue? If so, is there a release I can find it in?

**Comment by RobWin** [comment]
The resilience4j Spring Boot Starter allows you to add Resilience4j annotations like `@CircuitBreaker` to an interface with a `@FeignClient` annotation.
Is that what you are looking for @mraible?

**Comment by mraible** [comment]
Thanks for the tip @RobWin!

**Comment by typekpb** [comment]
@RobWin thanks! Any chance to include fallback implementation into your example?

**Comment by vchrisb** [comment]
@RobWin isn`t `resilience4j-spring-boot2` dependency missing in the starter to add `@CircuitBreaker` support?

**Comment by timpamungkas** [comment]
Following. It will be nice to has hystrix-like feature (e.g. fallback)

**Comment by RobWin** [comment]
@vchrisb The Resilience4j Spring Boot Starter and Spring Cloud CircuitBreaker are too separate projects.

**Comment by RobWin** [comment]
@typekpb @timpamungkas 

```
@FeignClient(name = "test", url = "http://url-do-not-exist")
public interface TestFeignClient {
    @GetMapping("test")
    @RateLimiter(name = "test", fallbackMethod = "test2")
    public String test();

    default String test2(Throwable throwable) {
        return "fallback";
    }
}
```

But I don't see how you can implement a meaningful fallback at this level without the need for DI.
I would implement a fallback outside of the interface.

**Comment by timpamungkas** [comment]
@RobWin 
Yes, I need to implement a fallback outside interface.  
In my case, I need to take default value from redis, so class implementation will be better design.  
In hystrix, I'd create the implementation of OpenFeign interface, and process there.   
In resilience4J, this code does not works

```java
@FeignClient(name = "industrialRelationClient", url = "http://localhost:8882")
public interface IndustrialRelationClient {

	@GetMapping(value = "/ping")
	@CircuitBreaker(name = "industrialRelationClient", fallbackMethod = "ping")
	public String ping();

}
```

```
public class IndustrialRelationCircuitBreaker implements IndustrialRelationClient {

	@Override
	public String ping() {
		return "Default ping";
	}

}
```

Throw an error
```
java.lang.NoSuchMethodException: class java.lang.String class com.sun.proxy.$Proxy109.ping(,class java.lang.Throwable)
```

**Comment by RobWin** [comment]
The only other way to do it, is to define your own bean as follows:

```
FeignDecorators decorators = FeignDecorators.builder()
            .withCircuitBreaker(circuitBreaker)
            .withFallback(industrialRelationCircuitBreaker)
            .build();
return Resilience4jFeign.builder(decorators)
            .target(IndustrialRelationClient.class, url);
```

Maybe you would like to contribute other options to Resilience4j? :)

**Comment by asrocket** [comment]
Works for me
```java
@FeignClient(name = ProducerClient.SERVICE_NAME, configuration = ProducerClientConfiguration.class)
public interface ProducerClient {
    String SERVICE_NAME = "producer-service";

    @CircuitBreaker(name = SERVICE_NAME)
    @RequestMapping(value = "/word", method = RequestMethod.GET)
    String getWord();
}

@RequiredArgsConstructor
public class ProducerClientConfiguration {
    private final CircuitBreakerRegistry registry;
    private final FallbackProducerClient fallbackProducerClient;

    @Bean
    @Scope("prototype")
    public Feign.Builder feignBuilder() {
        CircuitBreaker circuitBreaker = registry.circuitBreaker(ProducerClient.SERVICE_NAME);
        FeignDecorators decorators = FeignDecorators.builder()
                .withCircuitBreaker(circuitBreaker)
                .withFallback(fallbackProducerClient)
                .build();
        return Resilience4jFeign.builder(decorators);
    }
}

@Component
public class FallbackProducerClient implements ProducerClient {

    @Override
    public String getWord() {
        return "Hello (fallback)";
    }
}
```

**Comment by SoftwareKing** [comment]
@asrocket  Can you share this demo？

**Comment by eltonsandre** [comment]
Try this

`@FeignClient(name = ApiClient.CLIENT_NAME, url = "${client.api.url-base}")
public interface ApiClient {

    String CLIENT_NAME = "apiClient";

    @CircuitBreaker(name = "apiClientYml", fallbackMethod = "fallback")
    @GetMapping("/api/resource")
    String getAny();

    default String fallback(final java.lang.Throwable throwable) {
        return "----------Fallback----------";
    }

}`

**Comment by eltonsandre** [comment]
`@FeignClient(name = ApiClient.CLIENT_NAME, url = "${client.api.url-base}")
public interface ApiClient {

    String CLIENT_NAME = "apiClient";

    @CircuitBreaker(name = "configYourClientYml", fallbackMethod = "fallback")
    @GetMapping("/produtos")
    String produtos();

    default String fallback(final java.lang.Throwable throwable) {
        return "----------Fallback----------";
    }

}`

**Comment by eltonsandre** [comment]
```@FeignClient(name = ApiClient.CLIENT_NAME, url = "${client.api.url-base}")
public interface ApiClient {

    String CLIENT_NAME = "apiClient";

    @CircuitBreaker(name = "configYourClientYml", fallbackMethod = "fallback")
    @GetMapping("/produtos")
    String produtos();

    default String fallback(final java.lang.Throwable throwable) {
        return "----------Fallback----------";
    }

}```

**Comment by eltonsandre** [comment]
`
@FeignClient(name = ApiClient.CLIENT_NAME, url = "${client.api.url-base}")
public interface ApiClient {

    String CLIENT_NAME = "apiClient";

    @CircuitBreaker(name = "configYourClientYml", fallbackMethod = "fallback")
    @GetMapping("/produtos")
    String produtos();

    default String fallback(final java.lang.Throwable throwable) {
        return "----------Fallback----------";
    }

}

`

**Comment by asrocket** [comment]
@eltonsandre Yes. But this example not working if you need handle request body or any client method parameters in your fallback method

**Comment by eltonsandre** [comment]
Maybe @asrocket , well, I implement in the example in my [github](https://github.com/eltonsandre/sample-resilience4j-circuitbreak) a strategy using feign with decode and handler that suits me well, maybe it is not the most adequate, but it is an example and or improvement. if you have any suggestions is welcome :+1:  . @SoftwareKing maybe it can be useful.

**Comment by thagul** [comment]
Now that https://github.com/spring-cloud/spring-cloud-openfeign/issues/286 has been completed, how can we use resilience4j/SC Load balancer with OpenFeign?

**Comment by SantoshKumarSubedi** [comment]
> Works for me
> 
> ```java
> @FeignClient(name = ProducerClient.SERVICE_NAME, configuration = ProducerClientConfiguration.class)
> public interface ProducerClient {
>     String SERVICE_NAME = "producer-service";
> 
>     @CircuitBreaker(name = SERVICE_NAME)
>     @RequestMapping(value = "/word", method = RequestMethod.GET)
>     String getWord();
> }
> 
> @RequiredArgsConstructor
> public class ProducerClientConfiguration {
>     private final CircuitBreakerRegistry registry;
>     private final FallbackProducerClient fallbackProducerClient;
> 
>     @Bean
>     @Scope("prototype")
>     public Feign.Builder feignBuilder() {
>         CircuitBreaker circuitBreaker = registry.circuitBreaker(ProducerClient.SERVICE_NAME);
>         FeignDecorators decorators = FeignDecorators.builder()
>                 .withCircuitBreaker(circuitBreaker)
>                 .withFallback(fallbackProducerClient)
>                 .build();
>         return Resilience4jFeign.builder(decorators);
>     }
> }
> 
> @Component
> public class FallbackProducerClient implements ProducerClient {
> 
>     @Override
>     public String getWord() {
>         return "Fallback";
>     }
> }
> ```

What about passing exception to feedback method, any options there ?

**Comment by thagul** [comment]
I've discovered that resilience4j/SC Load balancer and OpenFeign integration now works without any further configuration. I was having problem because of a bug in Spring Cloud Sleuth https://github.com/spring-cloud/spring-cloud-sleuth/issues/1816

**Comment by ryanjbaxter** [comment]
Implemented in Spring Cloud OpenFeign https://github.com/spring-cloud/spring-cloud-openfeign/issues/279
