### ISSUE TITLE
No class org.springframework.boot.actuate.AbstractEndpoint

### ISSUE THREAD

**Issue by duffymo** [spring-cloud/spring-cloud-circuitbreaker#36]
I'm trying to add circuit breaker to a REST template using the circuit breaker project from the Spring Cloud incubator.

I've added the dependency to my pom.xml.   My parent is Spring Boot starter parent version 2.1.5.RELEASE:

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-circuitbreaker-spring-retry</artifactId>
            <version>0.0.1.BUILD-SNAPSHOT</version>
        </dependency>
```

I've tried both Resilience4J and SpringRetry circuit breakers for my client, but I get an exception at runtime: 

```java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/AbstractEndpoint```

I see an ```AbstractExposableEndpoint.class``` in the spring-boot-starter-actuator.jar.  Does the incubator dependency have to be updated to extend this class?

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by ryanjbaxter** [comment]
ping @duffymo

**Comment by ryanjbaxter** [comment]
Closing due to lack of feedback
