### ISSUE TITLE
Spring Cloud Sleuth Tracing info not passing to downstream services when using spring-cloud-circuitbreaker with resilience4j

### ISSUE THREAD

**Issue by sivaprasadreddy** [spring-cloud/spring-cloud-circuitbreaker#40]
I have microservices setup using SpringBoot and I have distributed tracing setup using SpringCloud Sleuth and Zipkin and the tracing is working as expected.

However, when I start using Spring Cloud CircuitBreaker while calling the downstream services using RestTemplate then tracing is broken ie the parent traceId is not passed to downstream service.

`cbFactory.create("getProductById").run(() -> restTemplate.getForObject(catalogSvcUrl+"api/products/"+id, Product.class))
`

But if I don't apply CircuitBreaker then Slueth tracing is working fine.

`restTemplate.getForObject(catalogSvcUrl+"api/products/"+id, Product.class))` //this is working fine.

Is there any way to make the sleuth tracing info (headers) pass to downstream services while using Spring Cloud CurcuitBreaker?

**Comment by ryanjbaxter** [comment]
@sivaprasadreddy I am not able to reproduce this issue, can you please provide a sample to reproduce the problem

**Comment by ryanjbaxter** [comment]
Closing due to lack of feedback

**Comment by sivaprasadreddy** [comment]
I tried with 0.0.1.BUILD-SNAPSHOT version with which I got this error. Now I tried with 1.0.0.RELEASE version and it is working fine.
