### ISSUE TITLE
Add Spring Cloud CircuitBreaker To Initializr

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-circuitbreaker#45]

**Comment by bono007** [comment]
@ryanjbaxter - I have been working a bit in Initializr (I have a few PRs over there) and we have a custom installation at my company. I am saying that to say that I am fairly familiar w/ it and would love to take this issue. Unless I hear otherwise I will start heading in that direction.

**Comment by bono007** [comment]
Created issue in [nitializr](https://github.com/spring-io/initializr/issues/1032) for this. Will see if there is any pushback from team there.

**Comment by bono007** [comment]
My above issue was closed as it was invalid - there is already the necessary ticket https://github.com/spring-io/start.spring.io/issues/319 .

**Comment by ryanjbaxter** [comment]
Closing in favor of the start.spring.io issue
