### ISSUE TITLE
Add an option to integrate with micrometer out of the box

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-circuitbreaker#47]
if I didn't do sth wrong then currently we need to pass quite a few setup for micrometer and resilience4j integration. It would great to have an option to allow adding a customization to any circuitbreaker (regardless of the id). 

This is how I worked this around ATM:

`pom.xml`

```

		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
			<version>${micrometer-registry-prometheus.version}</version>
		</dependency>
<!-- I had to manually pass the version of resilience4j -->
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-micrometer</artifactId>
			<version>${resilience4j.version}</version>
		</dependency>
```

Configuration class

```
@Bean
	Customizer<Resilience4JCircuitBreakerFactory> defaultCustomizer(CircuitBreakerRegistry circuitBreakerRegistry, MeterRegistry meterRegistry) {
		return factory -> {
			factory.configureDefault(id -> new Resilience4JConfigBuilder(id)
					.timeLimiterConfig(TimeLimiterConfig.custom()
							.timeoutDuration(Duration.ofSeconds(2))
							.build())
					.circuitBreakerConfig(CircuitBreakerConfig.ofDefaults())
					.build());
			// for metrics
			factory.configureCircuitBreakerRegistry(circuitBreakerRegistry);
			// we need to allow adding those customizers regardless of the id
			factory.addCircuitBreakerCustomizer(circuitBreaker -> {
				CircuitBreakerMetrics
						.ofCircuitBreakerRegistry(circuitBreakerRegistry)
						.bindTo(meterRegistry);
			}, "verifyNewUser");
		};
	}

	@Bean
	CircuitBreakerRegistry resilience4JCircuitBreakerRegistry() {
		return CircuitBreakerRegistry.ofDefaults();
	}
```

Circuit breaker

```
circuitBreakerFactory.create("verifyNewUser")
					.run(() -> restTemplate.getForObject(uriComponentsBuilder.toUriString(),
							VerificationResult.class), throwable -> userRejected(userUuid, userAge));
```

**Comment by making** [comment]
I’ve ever also digged into monitoring resillience4j with spring cloud circuit breaker. The next two points were concerns. 

1. `addCircuitBreakerCustomizer` requires all CircuitBreaker's ids. `CircuitBreakerRegistry.getAllCircuitBreaker` is the method to get all CBs. However, it’s difficult to retrieve all at the initializing phase. `getAllCircuitBreaker` will return empty list at the init phase as spring cloud circuit breaker creates and register a circuit breaker  in the registry at the actual execution phase. So we need to put all known ids to `addCircuitBreakerCustomizer` in the configuration in advance...
2. `TaggedCircuitBreakerMetrics.bindTo(MeterRegistry)` calls [`CircuitBreakerRegistry.getAllCircuitBreaker`](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/TaggedCircuitBreakerMetrics.java#L61) above and `addMetrics` to each CB. If we call `TaggedCircuitBreakerMetrics.bindTo` in the `Customizer<CircuitBreaker>`, which is the only customizable point as far as I know, every time when a CB is created, `addMetrics` for all CBs will be called. It’s quite inefficient. I’m not sure it really works.

With these restrictions, I came down to the implementation like following at that time,

```java
	@Bean
	public Customizer<ReactiveResilience4JCircuitBreakerFactory> resilience4jCustomizer(
			MeterRegistry registry, BlogProperties props) {
		ConcurrentMap<String, Boolean> registered = new ConcurrentHashMap<>();
		return factory -> {
			factory.addCircuitBreakerCustomizer(circuitBreaker -> {
				this.configureMetrics(registry, circuitBreaker, registered);
				this.configureEventPublisher(circuitBreaker.getEventPublisher());
			}, "myCb1", "myCb2", "myCb3", "myCb4", "myCb5" /* ... */);
			// ommited
		};
	}


	private void configureMetrics(MeterRegistry registry, CircuitBreaker circuitBreaker,
			ConcurrentMap<String, Boolean> registered) {
		TaggedCircuitBreakerMetrics.MetricNames names = TaggedCircuitBreakerMetrics.MetricNames
				.ofDefaults();
		String circuitBreakerName = circuitBreaker.getName();
		if (!registered.containsKey(circuitBreakerName)) {
			registered.putIfAbsent(circuitBreakerName, true);
			log.info("Register metric for {}", circuitBreaker);
			// Copy from AbstractCircuitBreakerMetrics
			Gauge.builder(names.getStateMetricName(), circuitBreaker,
					(cb) -> cb.getState().getOrder())
					.tag(TagNames.NAME, circuitBreakerName).register(registry);
			Gauge.builder(names.getCallsMetricName(), circuitBreaker,
					(cb) -> cb.getMetrics().getNumberOfFailedCalls())
					.tag(TagNames.NAME, circuitBreakerName).tag(TagNames.KIND, "failed")
					.register(registry);
			Gauge.builder(names.getCallsMetricName(), circuitBreaker,
					(cb) -> cb.getMetrics().getNumberOfNotPermittedCalls())
					.tag(TagNames.NAME, circuitBreakerName)
					.tag(TagNames.KIND, "not_permitted").register(registry);
			Gauge.builder(names.getCallsMetricName(), circuitBreaker,
					(cb) -> cb.getMetrics().getNumberOfSuccessfulCalls())
					.tag(TagNames.NAME, circuitBreakerName)
					.tag(TagNames.KIND, "successful").register(registry);
			Gauge.builder(names.getBufferedCallsMetricName(), circuitBreaker,
					(cb) -> cb.getMetrics().getNumberOfBufferedCalls())
					.tag(TagNames.NAME, circuitBreakerName).register(registry);
			Gauge.builder(names.getMaxBufferedCallsMetricName(), circuitBreaker,
					(cb) -> cb.getMetrics().getMaxNumberOfBufferedCalls())
					.tag(TagNames.NAME, circuitBreakerName).register(registry);
		}
	}
```

When using resillience4j directly without spring cloud circuit breaker, it’s usual to create a `CircuitBreaker` at the initializing phase. Then we can achieve register all CBs to `MeterRegistry` as follows:

```java
	@Bean
	public InitializingBean init(MeterRegistry meterRegistry, CircuitBreakerRegistry circuitBreakerRegistry) {
		return () -> TaggedCircuitBreakerMetrics.ofCircuitBreakerRegistry(circuitBreakerRegistry).bindTo(meterRegistry);
	}
```

**Comment by making** [comment]
I've created a simple project

Here is a project that uses resillience4j without spring cloud circuit breaker
https://github.com/making/demo-sccb-gh47/tree/master/demo-webflux-r4j
It looks easier to give the out of the box support for micrometer

To get the same experience with spring cloud circuit breaker, a project looks like
https://github.com/making/demo-sccb-gh47/tree/master/demo-webflux-sccb-r4j
Seems to need to change something in spring cloud circuit breaker

**Comment by ryanjbaxter** [comment]
@making @marcingrzejszczak 

I could see making this simpler, but I am really curious about @making's experience

I could see metrics for my CB just by doing the following

```
@Bean
	public Customizer<Resilience4JCircuitBreakerFactory> defaultCustomizer(MeterRegistry meterRegistry) {
		CircuitBreakerRegistry cbr = CircuitBreakerRegistry.ofDefaults();
		TaggedCircuitBreakerMetrics.ofCircuitBreakerRegistry(cbr).bindTo(meterRegistry);
		return factory -> {
			factory.configureDefault(id -> new Resilience4JConfigBuilder(id)
					.timeLimiterConfig(TimeLimiterConfig.custom().timeoutDuration(Duration.ofSeconds(3)).build())
					.circuitBreakerConfig(CircuitBreakerConfig.ofDefaults())
					.build());
			factory.configureCircuitBreakerRegistry(cbr);
		};
	}
```

This was in a non-reactive app, is the experience with a reactive app different?

**Comment by making** [comment]
> This was in a non-reactive app, is the experience with a reactive app different?

I've confirmed my sample works after applying same changes in #51 👍

What I misunderstood is that all circuit breakers must be registered when `TaggedCircuitBreakerMetrics` is created but It doesn't.
https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/TaggedCircuitBreakerMetrics.java#L66-L69

**Comment by ryanjbaxter** [comment]
@making thanks for confirming!

**Comment by RobWin** [comment]
If you have questions in the future about Resilience4j, don't hesitate to ping us.
Did you test if your auto configuration works together with Spring Cloud Config? We added some new classes to support it, like https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/TaggedCircuitBreakerMetricsPublisher.java
