### ISSUE TITLE
Configure the circuit breaker throug config file and run time reload through spring cloud config ?

### ISSUE THREAD

**Issue by Romeh** [spring-cloud/spring-cloud-circuitbreaker#49]
I have a question , do have any examples of how to configure the circuit breakers through spring config files and if the configuration be dynamically changed at rune time through spring cloud config for example ?

**Comment by ryanjbaxter** [comment]
@Romeh what aspects are you looking to configure?

**Comment by Romeh** [comment]
@ryanjbaxter for example if i am using spring cloud circuit breaker resilience4j starter and i need to configure some properties of a custom circuit breaker like window size...ect , I can do that through the existing spring cloud starter or it need to be extended for that ?

**Comment by ryanjbaxter** [comment]
Have you tried this https://github.com/resilience4j/resilience4j-spring-boot-demo#configuration

**Comment by Romeh** [comment]
yes it is based into resilience4j spring boot starter not the spring cloud circuit breaker starter , no plan to support the same ?

**Comment by Romeh** [comment]
I manged to merge the usage of resilience4j spring boot starter with spring cloud starter for external Spring configuration of resilienec4j circuit breakers ! thx for your help !
