### ISSUE TITLE
Resilience4J Configurations from application.yml aren't Supported

### ISSUE THREAD

**Issue by timothymathison** [spring-cloud/spring-cloud-circuitbreaker#61]
**Description:**

Application: `spring-cloud-gateway:Hoxton.SR3`
Circuit-Breaker version: `1.0.2.RELEASE`

As far as I can tell, yaml configurations are ignored. The provided [`ReactiveResilience4JCircuitBreakerFactory` bean](https://github.com/spring-cloud/spring-cloud-circuitbreaker/blob/5312e3d2a7f85b5bab1297cebaf573fc3d854903/spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/ReactiveResilience4JAutoConfiguration.java#L54) uses the [default `CircuitBreakerRegistry`](https://github.com/spring-cloud/spring-cloud-circuitbreaker/blob/5312e3d2a7f85b5bab1297cebaf573fc3d854903/spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreakerFactory.java#L45) which only uses the hard-coded defaults. I tried creating my own `ReactiveResilience4JCircuitBreakerFactory` bean which uses the `CircuitBreakerRegistry` from [here](https://github.com/resilience4j/resilience4j/blob/54a2b1b907c7a8f00737c7ea784fab2ecdd462cb/resilience4j-spring-cloud-common/src/main/java/io/github/resilience4j/circuitbreaker/autoconfigure/AbstractRefreshScopedCircuitBreakerConfiguration.java#L33). However, `spring-cloud-circuit-breaker` seems to ignore resiliency4j configurations defined for the registry. I think that is because of [this logic](https://github.com/spring-cloud/spring-cloud-circuitbreaker/blob/5312e3d2a7f85b5bab1297cebaf573fc3d854903/spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/ReactiveResilience4JCircuitBreakerFactory.java#L52) which pulls configurations from [here](https://github.com/spring-cloud/spring-cloud-commons/blob/9441a25938dabdb971db93165e9f2a23c54362cc/spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/AbstractCircuitBreakerFactory.java#L51); but it seems like `configure` is never called, so that `configurations` map is always empty. Therefore, it always falls back to the [defaults](https://github.com/spring-cloud/spring-cloud-circuitbreaker/blob/5312e3d2a7f85b5bab1297cebaf573fc3d854903/spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/ReactiveResilience4JCircuitBreakerFactory.java#L40).
As a result, every `CircuitBreaker` is [created with those defaults](https://github.com/spring-cloud/spring-cloud-circuitbreaker/blob/5312e3d2a7f85b5bab1297cebaf573fc3d854903/spring-cloud-circuitbreaker-resilience4j/src/main/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreaker.java#L73). Does anyone know why the `circuitBreaker(id, configs)` method is being used instead of one of the other methods like [`circuitBreaker(id)`](https://github.com/resilience4j/resilience4j/blob/54a2b1b907c7a8f00737c7ea784fab2ecdd462cb/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/InMemoryCircuitBreakerRegistry.java#L92) which uses the configurations set for the `CircuitBreakerRegistry`?

Is there some existing logic I'm missing? If not would it be possible to change the implementation to support providing `resilience4J` configurations from `application.yml`?

**Comment by ryanjbaxter** [comment]
You can provide default configuration for all circuit breakers as outlined here in the documentation https://cloud.spring.io/spring-cloud-static/spring-cloud-circuitbreaker/1.0.0.RELEASE/reference/html/#default-configuration

You can also provide configuration for a specific circuit breaker

https://cloud.spring.io/spring-cloud-static/spring-cloud-circuitbreaker/1.0.0.RELEASE/reference/html/#specific-circuit-breaker-configuration

We do not currently use properties from application properties.

**Comment by timothymathison** [comment]
Unfortunately, there isn't a straight forward way to configure different environments separately using the code approach outlined in the documentation (without implementing our own .

**Comment by timothymathison** [comment]
Closed by accident.

**Comment by ryanjbaxter** [comment]
I am unsure what you mean by "environments"

**Comment by timothymathison** [comment]
> I am unsure what you mean by "environments"

Sorry for the confusion. I mean't _"different profiles"_.

**Comment by spencergibb** [comment]
Have you tried `@Profile`?

**Comment by timothymathison** [comment]
@spencergibb, No I haven't; I forgot that `@Profile` is an option in this case.
I think in-code configurations should be sufficient for our current uses.

However, wouldn't support for external/remote configurations still be a worthwhile feature to have, for the same reasons that external configurations are supported by other Spring packages?

**Comment by Romeh** [comment]
@timothymathison  here you can find an example how to mix resilience4j spring boot starter and spring cloud circuit breaker starter to enable external application yaml configuration of your circuit breaker and time limiter as well : 
https://github.com/Romeh/spring-cloud-gateway-resilience4j

**Comment by rajashashankmuppirala** [comment]
@timothymathison , I had a similar requirement and I was able to configure it as below.

```java
        @Bean
	public ReactiveResilience4JCircuitBreakerFactory reactiveResilience4JCircuitBreakerFactory(final CircuitBreakerRegistry circuitBreakerRegistry, final TimeLimiterRegistry timeLimiterRegistry) {
		ReactiveResilience4JCircuitBreakerFactory reactiveResilience4JCircuitBreakerFactory = new ReactiveResilience4JCircuitBreakerFactory();
		reactiveResilience4JCircuitBreakerFactory.configureCircuitBreakerRegistry(circuitBreakerRegistry);
		reactiveResilience4JCircuitBreakerFactory.configureDefault(id -> {
			CircuitBreakerConfig circuitBreakerConfig = circuitBreakerRegistry.find(id).isPresent() ? circuitBreakerRegistry.find(id).get().getCircuitBreakerConfig()
					: circuitBreakerRegistry.getDefaultConfig();
			TimeLimiterConfig timeLimiterConfig = timeLimiterRegistry.find(id).isPresent() ? timeLimiterRegistry.find(id).get().getTimeLimiterConfig()
					: timeLimiterRegistry.getDefaultConfig();

			return new Resilience4JConfigBuilder(id)
					.circuitBreakerConfig(circuitBreakerConfig)
					.timeLimiterConfig(timeLimiterConfig)
					.build();
		});
		return reactiveResilience4JCircuitBreakerFactory;
	}

```

**Comment by ryanjbaxter** [comment]
@Romeh thanks for the example!

Basically all you need is the r4j spring boot starter on the classpath and then you can configure the CB and time limiter via coniguration properties.  The starter creates the beans and then those beans are used by your custom config.

Is that the basic idea?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by dalegaspi** [comment]
@Romeh actually that doesn't really work 100%.  for https://github.com/Romeh/spring-cloud-gateway-resilience4j/blob/f74cdcdc226fb782e2adc8af9dd84f0f32ab482a/src/main/java/io/github/romeh/services/gateway/GatewayApplication.java#L28 the `timeLimiterRegistry.getConfiguration("backendB")` will actually return `Optional.Empty` even if you have `backendB` defined in your `application.yml` (i know because i tried) so it will always fall back to the `.orElse(...)` part.

**Comment by dalegaspi** [comment]
@rajashashankmuppirala's solution is (IMO) better and it actually works (i just tried it).  it would at least defer fully on application.yml for configuration (and overrides) for the timeout.

**Comment by Ferioney** [comment]
@ryanjbaxter We have a lot of configuration properties for Hystrix (like [Hystrix command properties](https://github.com/Netflix/Hystrix/wiki/Configuration#CommandProperties)). And it would be nice to have a possibility to migrate Hystrix properties to the Resilience4J properties. 
Now I see just one way to configure CircuitBreaker/TimeTimit by using `Customizer<Resilience4JCircuitBreakerFactory>`. It very difficult to migrate Hystrix's properties to java Customizer.

It would be nice to add this possibility to `spring-cloud-starter-circuitbreaker-resilience4j` module. I think it pretty simple (I can help with contributing). All that we need is add a dependency to the `resilience4j-spring-boot2` module and add CircuitBreakerRegistry (TimeLimitRegistry and BulkheadRegistry in the future) bean to the `Resilience4JCircuitBreakerFactory`. To my mind it will be very helpful for all people who want to migrate from Hystrix to Resilience4j

**Comment by ryanjbaxter** [comment]
@Ferioney always happy to have contributions!

**Comment by timothymathison** [comment]
It looks like #88 didn't include changes for `ReactiveResilience4JCircuitBreakerFactory` which was the context for my original request when I opened this issue. So I don't think this issue should have been closed. However, I see that #108 has been opened specifically for the reactive version.

**Comment by ryanjbaxter** [comment]
@atulkumar-mittal can you elaborate on what versions you were using that were incompatible?
