### ISSUE TITLE
Wrong dependency reactive resilience4j name in https://spring.io/projects/spring-cloud-circuitbreaker

### ISSUE THREAD

**Issue by aboukleev** [spring-cloud/spring-cloud-circuitbreaker#64]
In documentation  https://spring.io/projects/spring-cloud-circuitbreaker, the dependency name for
Reactive Resilience4J is misspelled: org.springframework.cloud:spring-cloud-starter-circuitbreaker-**reator**-resilience4j

**Comment by ryanjbaxter** [comment]
Fixed thanks!
