### ISSUE TITLE
Upgrade resilience4j from 1.1.0 to 1.3.1

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-cloud/spring-cloud-circuitbreaker#65]
`resilience4j 1.1.0` was released on 2019-09-30.  `1.3.1` was released on 2020-02-06 about 2 months ago and isn't brand-new anymore. Please see:

https://github.com/spring-cloud/spring-cloud-circuitbreaker/blob/master/spring-cloud-circuitbreaker-dependencies/pom.xml#L21

**Comment by ryanjbaxter** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-circuitbreaker/commit/8aceda2a6312d95360eb99beb28b2840460f2f1c
