### ISSUE TITLE
why circuitbreaker recordexceptions attribute in spring cloud does not work? 

### ISSUE THREAD

**Issue by luguoji** [spring-cloud/spring-cloud-circuitbreaker#66]
![1](https://user-images.githubusercontent.com/63774857/79426072-34eec600-7ff5-11ea-9aeb-83e562d7611f.png)

I am using cloud gateway circuitbreaker,  find the method **<T> Mono<T> run(Mono<T> toRun, Function<Throwable, Mono<T>> fallback)**  only handle **TimeoutException**, the recordexceptions  of CircuitBreakerConfig does not work，such as  java.lang.RuntimeException。Looks like it is bug。

**Comment by ryanjbaxter** [comment]
The code is there specifically in the reactive case because we are using Project Reactor's timeout api and R4J will not handle a timeout from reactor like it would if we were using an R4J timeout.

**Comment by luguoji** [comment]
Thanks for your reply. When I used cloud gateway, the downstream uri has runtimexception, but R4J does not CircuitBreak. I try to config the RecordExceptions，add java.lang.RuntimeException. But it still doesn't work. I hope I can get your help and support. Thanks you very much.

**Comment by luguoji** [comment]
Currently, only TimeOutException trigger CircuitBreak, other exceptions does not work. Is it a problem?

**Comment by landyking** [comment]
> Currently, only TimeOutException trigger CircuitBreak, other exceptions does not work. Is it a problem?

Other exceptions also can be recorded. See here `io.github.resilience4j.reactor.circuitbreaker.operator.CircuitBreakerSubscriber#hookOnError`

**Comment by ryanjbaxter** [comment]
Is the downstream service returning a specific status code when the exception is thrown?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by IlyaPavlovV** [comment]
> > Currently, only TimeOutException trigger CircuitBreak, other exceptions does not work. Is it a problem?
> 
> Other exceptions also can be recorded. See here `io.github.resilience4j.reactor.circuitbreaker.operator.CircuitBreakerSubscriber#hookOnError`. If you want the circuit breaker to work with the response status code, you can write a gateway filter to check the status code and throw custom exceptions. Then `CircuitBreakerSubscriber#hookOnError` will catch and record the failure request.

Hello! I had same problem like author has, and I had follow this advice and it was very helpful for me. But now circuitbreaker's fallback method is called every time when downstream service returning http status code exception, even ciruitbreaker state is closed. Is it possible to use this way to intercept not only TimeOutException and call fallback method only when circuitbreaker is open?

**Comment by ryanjbaxter** [comment]
Please open a separate issue and provide a sample
