### ISSUE TITLE
what does  the difference between Spring Cloud Commons and  spring-cloud-circuitbreaker

### ISSUE THREAD

**Issue by yuanjinzhong** [spring-cloud/spring-cloud-circuitbreaker#70]
when i want to use  circuitbreaker, i dont know which libary should be dependencied?

Spring Cloud Commons  or   spring-cloud-circuitbreaker？

i have no idea about the difference, anyone can help ?

thanks

**Comment by ryanjbaxter** [comment]
It really depends on the implementation you want to use.  Spring Cloud Commons just contains the interfaces.  Spring Cloud CircuitBreaker contains most of the implementations.  However some of the implementations live in other projects, like Sentinal.

**Comment by yuanjinzhong** [comment]
Spring Cloud Commons just a high level interface , i think.

**Comment by ryanjbaxter** [comment]
Correct, that is what I said in my comment above.
