### ISSUE TITLE
Unable to access resilience4j metrics via actuator.

### ISSUE THREAD

**Issue by Abhisar** [spring-cloud/spring-cloud-circuitbreaker#83]
I am unable to access resilience4j metrics in my spring boot project via actuator .
I have added the following dependencies 
                 
                  `<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
			<version>1.0.4.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
			<version>2.3.5.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-micrometer</artifactId>
			<version>1.6.1</version>
		</dependency>
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-circuitbreaker</artifactId>
			<version>1.6.1</version>
		</dependency>`

**Comment by ryanjbaxter** [comment]
Please use the BOM for bother Spring Cloud and Spring Boot

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
