### ISSUE TITLE
addCircuitBreakerCustomizer register events in each time when method called

### ISSUE THREAD

**Issue by Ferioney** [spring-cloud/spring-cloud-circuitbreaker#89]
When you use Resilience4JCircuitBreakerFactory.addCircuitBreakerCustomizer() to customize an event, this event will be added in every call of the method.

We customize circuitBreaker each time when calling a method. But circuitBreaker is stored in circuitBreakerRegistry. so each time we add an event to this circuitBreaker.

In Resilience4j events store as map, that why it possible:
[EventProcessor](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-core/src/main/java/io/github/resilience4j/core/EventProcessor.java#L41)

Unit test that shows defect:
[defectTwoSlowCircuitBreakerConsumerShouldBeCalledTwoTimesButCalledThreeTimes](https://github.com/Ferioney/spring-cloud-circuitbreaker/blob/defect_addCircuitBreakerCustomizer/spring-cloud-circuitbreaker-resilience4j/src/test/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreakerIntegrationTest.java#L116)

**Comment by ryanjbaxter** [comment]
If we don't call the `create` method when `normal` is called I think that would solve the problem no?

**Comment by ryanjbaxter** [comment]
https://github.com/Ferioney/spring-cloud-circuitbreaker/blob/defect_addCircuitBreakerCustomizer/spring-cloud-circuitbreaker-resilience4j/src/test/java/org/springframework/cloud/circuitbreaker/resilience4j/Resilience4JCircuitBreakerIntegrationTest.java#L198

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by limng06** [comment]
it happened . the circuitbreaker always customize itselef in the “run” method and the event consumer will be added again

**Comment by ryanjbaxter** [comment]
@Ferioney @limng06 can you confirm if this is still a problem with the latest release Spring Cloud 2021.0.0?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
