### ISSUE TITLE
[question] include Bulkhead and Spring Boot property configuration to the Hoxton.SR11

### ISSUE THREAD

**Issue by Ferioney** [spring-cloud/spring-cloud-circuitbreaker#93]
Is it possible to include features [Resilience4J Configurations from application.yml aren't Supported](https://github.com/spring-cloud/spring-cloud-circuitbreaker/issues/61) and [Use Resilience4J Bulkhead Module](https://github.com/spring-cloud/spring-cloud-circuitbreaker/issues/86) to the Spring Cloud [Hoxton.SR11](https://github.com/spring-cloud/spring-cloud-release/milestone/103)? Thanks.

**Comment by ryanjbaxter** [comment]
I cherry picked the commits, and they should be in snapshot releases if you want to give them a try.
